Add cleanup step for unused packages in workflow
Added a cleanup step to remove unused packages and SDKs to free up disk space during the build process.

diff --git a/.github/workflows/reuse_build_test_qemu_image.yml b/.github/workflows/reuse_build_test_qemu_image.yml
--- a/.github/workflows/reuse_build_test_qemu_image.yml
+++ b/.github/workflows/reuse_build_test_qemu_image.yml
@@ -36,8 +36,37 @@ env:
 jobs:
   build:
     runs-on: ${{ inputs.runs-on }}
-    container: ubuntu:24.04
     steps:
+      - name: Cleanup unused packages to free disk space
+        run: |
+          echo "Removing top large packages"
+          packages=(
+            google-chrome-stable microsoft-edge-stable firefox
+            azure-cli google-cloud-cli kubectl podman skopeo buildah snapd
+            temurin-8-jdk temurin-11-jdk temurin-17-jdk temurin-21-jdk
+            dotnet-sdk-8.0 dotnet-runtime-8.0 aspnetcore-runtime-8.0 aspnetcore-targeting-pack-8.0 netstandard-targeting-pack-2.1-8.0 dotnet-targeting-pack-8.0
+            llvm-16-dev llvm-17-dev llvm-18-dev
+            clang-tools-16 clang-tools-17 clang-tools-18
+            clang-tidy-16 clang-tidy-17 clang-tidy-18
+          )
+          for pkg in "${packages[@]}"; do
+              if dpkg-query -W -f='${Package}\n' $pkg 2>/dev/null | grep -q .; then
+                  echo "Package $pkg exists, removing..."
+                  sudo apt-get remove -y --purge --allow-change-held-packages --allow-remove-essential --no-install-recommends $pkg || true
+              else
+                  echo "Package $pkg not found, skipping."
+              fi
+          done
+          sudo apt-get autoremove -y || true
+          sudo apt-get clean || true
+
+          echo "Removing heavy preinstalled SDKs..."
+          sudo rm -rf /usr/local/lib/android
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/hostedtoolcache
+          
+          echo "Disk usage after cleanup:"
+          df -h
       - name: Restore build cache
         uses: actions/cache@v4
         with:
